### ISSUE TITLE
Editor backup files in Repo

### ISSUE THREAD

**Issue by maxnoe** [Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE#1]
There are some editor backup files in the repo (Ending with `~`)
We should remove those and put it in the `.gitignore`.

**Comment by TarekHC** [comment]
My bad. Should be solved with 5e7b0a0bbd1b2a529896cbc6873a1e6798c40adc.

Close if you are happy now! :)

**Comment by maxnoe** [comment]
I cannot describe my joy with words!
