### ISSUE TITLE
Outdated tutorial in README

### ISSUE THREAD

**Issue by kbruegge** [Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE#2]
There is a link to a python tutorial for beginners in the README.md which seems horribly outdated. (Python 2.4?). Maybe instead use this one: https://www.learnpython.org ?

**Comment by TarekHC** [comment]
I personally like the code academy:
https://www.codecademy.com/learn/python

Opinions?

**Comment by kbruegge** [comment]
nice 👍

**Comment by stgriffi** [comment]
~~I also like codecademy.~~

Codecademy has changed a lot since I used it, and now it is less good. Also, it only supports Python 2! I vote instead for https://www.learnpython.org.

**Comment by stgriffi** [comment]
@mackaiver and @TarekHC: I updated the readme; can we close this?

**Comment by kbruegge** [comment]
I think so yes.
