### ISSUE TITLE
TODOs matplotlib

### ISSUE THREAD

**Issue by maxnoe** [Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE#3]
- [x] how to save plots
- [x] hist2d, matshow, imshow
- [x] styles / seaborn

**Comment by maxnoe** [comment]
Links <a> are broken

**Comment by stgriffi** [comment]
Links have been fixed. Added code for the "Shared Axis" section (there was nothing before).

**Comment by TarekHC** [comment]
Hi @MaxNoe, @stgriffi, @ftorradeflot,

If any of you have the time, I think it would make sense to add a couple of exercises. I know the notebook is very easy to follow, and the exercises are not THAT necessary... But the whole course could turn out to be too much "unidirectional" just plotting and plotting... 

If you guys agree and any of you still finds the time to add a couple of exercises it would be great. If you don't, don't worry about it! The notebook is already great as it is.
