### ISSUE TITLE
Numpy Notebook Improvments

### ISSUE THREAD

**Issue by maxnoe** [Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE#4]
1. More concrete (real-life) examples.
2. Show reshape.
3. vstack /hstack
4. IO with numpy

Maybe use np.random stuff to calculate PI?

**Comment by stgriffi** [comment]
Hi @MaxNoe , the Numpy notebook looks awesome! I really like your examples -- they are excellent, real-world physics problems. ~~I must admit, though, that I am a bit concerned about the difficulty level.~~

Actually, I took another look and I think the difficulty level is fine. Plus, I didn't notice there are solutions. Cheers!
