### ISSUE TITLE
Do not use pylab or %pylab inline

### ISSUE THREAD

**Issue by maxnoe** [Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE#5]
`pylab` and especially `%pylab inline` should not be shown or used.

These imports are overwriting builtins like `sum` and are generellay confusing where stuff comes from (numpy, matplotlib or scipy)

**Comment by stgriffi** [comment]
Agreed. There was one `pylab` import in the Scipy notebook from cut & paste code -- it has been removed (not committed yet, but soon!).

@serranoice : there are a few `pylab` imports in the Astronomy notebook.

**Comment by ssegraphics** [comment]
Yes, I will remove them. Sorry I am late.
