### ISSUE TITLE
TODOs for scipy unit

### ISSUE THREAD

**Issue by TarekHC** [Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE#7]
As asked by Manel, we could also give some info for using minuit with python.

We could simply add a link to [iminuit](http://iminuit.readthedocs.io/en/latest/), or put a quick example if anyone feels like it...

Later on I can add a link, and if anyone feels like adding an example, it would be also nice.

**Comment by maxnoe** [comment]
The examples in the docs are really good

**Comment by TarekHC** [comment]
Ok, I added one sentence about iminuit within https://github.com/Python4AstronomersAndParticlePhysicists/PythonWorkshop-ICE/commit/f1de2c85fd2d73c6f111987dd201a8ec09c1d4bc.

I don't see an example necessary, so I close the issue.
